### ISSUE TITLE
TXP 4.8.8 support

### ISSUE THREAD

**Issue by cara-tm** [gocom/rah_wrach#1]
This excellent plugin does not work with the next TXP version...

I tried to call a specific section from URL queries (`&Section=my-section`) without a corresponding choice within the “Write” panel.

It seems that the new “Default publishing section” selector from the “Section” panel overwrite these kinds of queries and the selection is now governed by Ajax…

**Comment by gocom** [comment]
Thank you for the report, Patrick.

Have to check this when/if I have some time in the future.

**Comment by cara-tm** [comment]
Thank you lot, Jukka: that's perfect!

I'm loving so much your plugin I suggested adding it into the Core as a default section view because it simplifies so the writing experience to authors.
